package autopilot

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"time"

	"github.com/google/uuid"

	"github.com/raghavkgarg/mycase/pkg/cache"
	"github.com/raghavkgarg/mycase/pkg/tax"
)

const (
	ProposalDir  = "data/autopilot"
	ProposalFile = "data/autopilot/pending_proposal.json"

	StatusPending   = "pending"
	StatusConfirmed = "confirmed"
	StatusDismissed = "dismissed"
	StatusExpired   = "expired"
)

// Proposal represents a pending rebalance proposal generated by the autopilot pipeline.
type Proposal struct {
	ID        string    `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
	Status    string    `json:"status"`

	// Portfolio context
	Portfolio string `json:"portfolio"` // golden copy path
	Strategy  string `json:"strategy"`  // e.g. "multibagger"
	Frequency string `json:"frequency"` // e.g. "quarterly"

	// Changes from previous golden copy
	Entries       []StockChange `json:"entries"`        // new additions
	Exits         []StockChange `json:"exits"`          // removals
	WeightChanges []WeightDelta `json:"weight_changes"` // reweighted existing stocks

	// Proposed orders
	Orders      []ProposedOrder `json:"orders"`
	FilteredOut []ProposedOrder `json:"filtered_out"` // micro-transaction filtered

	// Summary
	TotalBuyValue  float64  `json:"total_buy_value"`
	TotalSellValue float64  `json:"total_sell_value"`
	EstimatedCost  float64  `json:"estimated_cost"`
	TaxWarnings    []string `json:"tax_warnings"`

	// Report references
	ReportPath    string `json:"report_path"`
	SelectionPath string `json:"selection_path"`

	// Execution results (filled after confirmation)
	ConfirmedAt    *time.Time    `json:"confirmed_at,omitempty"`
	ExecutionLog   []OrderResult `json:"execution_log,omitempty"`
	ExecutionError string        `json:"execution_error,omitempty"`
}

// ProposedOrder represents a single order in the rebalance proposal.
type ProposedOrder struct {
	Ticker     string  `json:"ticker"`
	Exchange   string  `json:"exchange"`
	Action     string  `json:"action"` // "BUY" or "SELL"
	Quantity   int     `json:"quantity"`
	LimitPrice float64 `json:"limit_price"`
	Value      float64 `json:"value"`
}

// StockChange represents a stock entering or exiting the portfolio.
type StockChange struct {
	Ticker string  `json:"ticker"`
	Rank   int     `json:"rank"`
	Score  float64 `json:"score"`
	Weight float64 `json:"weight"`
	Reason string  `json:"reason"`
}

// WeightDelta represents a weight change for an existing holding.
type WeightDelta struct {
	Ticker    string  `json:"ticker"`
	OldWeight float64 `json:"old_weight"`
	NewWeight float64 `json:"new_weight"`
}

// OrderResult captures the outcome of placing a single order.
type OrderResult struct {
	Ticker  string `json:"ticker"`
	Action  string `json:"action"`
	OrderID string `json:"order_id,omitempty"`
	Success bool   `json:"success"`
	Error   string `json:"error,omitempty"`
}

// NewProposal creates a new proposal with the given TTL in days.
func NewProposal(portfolio, strategy, frequency string, ttlDays int) *Proposal {
	now := time.Now()
	return &Proposal{
		ID:        uuid.New().String(),
		CreatedAt: now,
		ExpiresAt: now.AddDate(0, 0, ttlDays),
		Status:    StatusPending,
		Portfolio: portfolio,
		Strategy:  strategy,
		Frequency: frequency,
	}
}

// IsExpired returns true if the proposal has passed its expiry time.
func (p *Proposal) IsExpired() bool {
	return time.Now().After(p.ExpiresAt)
}

// IsActionable returns true if the proposal can be confirmed or dismissed.
func (p *Proposal) IsActionable() bool {
	return p.Status == StatusPending && !p.IsExpired()
}

// SaveProposal persists the proposal to disk as JSON.
func SaveProposal(p *Proposal) error {
	if err := os.MkdirAll(ProposalDir, 0755); err != nil {
		return fmt.Errorf("creating autopilot directory: %w", err)
	}
	data, err := json.MarshalIndent(p, "", "  ")
	if err != nil {
		return fmt.Errorf("marshaling proposal: %w", err)
	}
	if err := os.WriteFile(ProposalFile, data, 0644); err != nil {
		return fmt.Errorf("writing proposal file: %w", err)
	}
	return nil
}

// LoadProposal reads the pending proposal from disk.
// Returns nil, nil if no proposal file exists.
func LoadProposal() (*Proposal, error) {
	data, err := os.ReadFile(ProposalFile)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("reading proposal file: %w", err)
	}
	var p Proposal
	if err := json.Unmarshal(data, &p); err != nil {
		return nil, fmt.Errorf("parsing proposal file: %w", err)
	}
	// Auto-expire if past TTL
	if p.Status == StatusPending && p.IsExpired() {
		p.Status = StatusExpired
		_ = SaveProposal(&p) // best-effort persist expiry
	}
	return &p, nil
}

// ConfirmProposal marks the proposal as confirmed and records the timestamp.
func ConfirmProposal(p *Proposal) error {
	if !p.IsActionable() {
		if p.IsExpired() {
			return fmt.Errorf("proposal %s has expired (expired at %s)", p.ID, p.ExpiresAt.Format(time.RFC3339))
		}
		return fmt.Errorf("proposal %s is not actionable (status: %s)", p.ID, p.Status)
	}
	now := time.Now()
	p.Status = StatusConfirmed
	p.ConfirmedAt = &now
	return SaveProposal(p)
}

// DismissProposal marks the proposal as dismissed without executing.
func DismissProposal(p *Proposal) error {
	if p.Status != StatusPending {
		return fmt.Errorf("proposal %s cannot be dismissed (status: %s)", p.ID, p.Status)
	}
	p.Status = StatusDismissed
	return SaveProposal(p)
}

// ArchiveProposal moves the current proposal to the archive directory.
func ArchiveProposal(p *Proposal) error {
	archiveDir := filepath.Join(ProposalDir, "archive")
	if err := os.MkdirAll(archiveDir, 0755); err != nil {
		return fmt.Errorf("creating archive directory: %w", err)
	}
	archiveName := fmt.Sprintf("%s_%s.json", p.CreatedAt.Format("20060102_150405"), p.Status)
	archivePath := filepath.Join(archiveDir, archiveName)

	data, err := json.MarshalIndent(p, "", "  ")
	if err != nil {
		return fmt.Errorf("marshaling proposal for archive: %w", err)
	}
	if err := os.WriteFile(archivePath, data, 0644); err != nil {
		return fmt.Errorf("writing archive file: %w", err)
	}
	// Remove the active proposal file
	_ = os.Remove(ProposalFile)
	return nil
}

// FinalStageProposals converts a confirmed proposal's *successfully-placed* orders
// into the []cache.Proposal records for the "final" pipeline stage.
//
// This is the executed-intent audit record (roadmap Phase 9): unlike the
// "optimized" stage — which captures the target basket the strategy proposed
// *before* confirmation — "final" reflects what the investor actually confirmed
// and submitted to the broker. Orders that failed to place are excluded, so the
// stage honestly records the executed roster, not the intended one.
//
// Weights are the executed BUY-side allocation: each held ticker's order value
// as a fraction of the total placed BUY value, mirroring how "optimized" weights
// are expressed (non-negative fractions summing to ~1). SELL orders reduce or
// exit a position and carry no target weight, so they are not weighted here; they
// still appear implicitly as absences relative to the previous run's selections.
//
// Order placement returns only an order id (no fill quantity/price — see
// pkg/broker/types.OrderResult), so these are submitted-intent weights derived
// from limit price × quantity, not realized fills. A realized-weight variant
// (reconciled from broker transactions) is a documented follow-up.
//
// Returns nil when no BUY orders were successfully placed (nothing to record).
func FinalStageProposals(p *Proposal) []cache.Proposal {
	if p == nil {
		return nil
	}

	// Index successful placements by ticker so we only record executed orders.
	placed := make(map[string]bool, len(p.ExecutionLog))
	for _, r := range p.ExecutionLog {
		if r.Success {
			placed[r.Ticker] = true
		}
	}

	// Sum executed BUY value for weight normalization.
	var totalBuy float64
	for _, o := range p.Orders {
		if o.Action == "BUY" && placed[o.Ticker] {
			totalBuy += o.Value
		}
	}
	if totalBuy <= 0 {
		return nil
	}

	proposals := make([]cache.Proposal, 0, len(p.Orders))
	rank := 0
	for _, o := range p.Orders {
		if o.Action != "BUY" || !placed[o.Ticker] {
			continue
		}
		rank++
		proposals = append(proposals, cache.Proposal{
			Ticker: o.Ticker,
			Weight: o.Value / totalBuy,
			Rank:   rank,
		})
	}
	return proposals
}

// RealizedStageProposals computes the *realized* "final" stage proposals from
// actual broker fills, superseding the submitted-intent weights that
// FinalStageProposals records at confirm time (roadmap Phase 9 follow-up).
//
// It aggregates the BUY-side executed dollar value per ticker
// (Σ quantity × price, fees excluded so weights reflect market allocation, not
// transaction drag) across all transactions whose TradedAt falls within
// [from, to], then normalizes to per-ticker weights (fractions summing to ~1)
// ranked by descending weight — the realized analogue of FinalStageProposals.
//
// Only BUY legs contribute weight: a SELL exits or trims a position and carries
// no target allocation, mirroring FinalStageProposals. Transactions outside the
// window (unrelated rebalances, dividends reinvested later) are ignored.
//
// The [from, to] bound is inclusive of from and exclusive of to. Returns nil
// when no BUY fills land in the window (nothing to reconcile).
func RealizedStageProposals(txns []tax.Transaction, from, to time.Time) []cache.Proposal {
	realized := make(map[string]float64)
	var total float64
	for _, t := range txns {
		if t.Type != tax.TxnBuy {
			continue
		}
		if t.TradedAt.Before(from) || !t.TradedAt.Before(to) {
			continue // outside [from, to)
		}
		value := t.Quantity * t.Price
		if value <= 0 {
			continue
		}
		realized[t.Ticker] += value
		total += value
	}
	if total <= 0 {
		return nil
	}

	// Deterministic order: descending realized value, ticker as tiebreak.
	tickers := make([]string, 0, len(realized))
	for tk := range realized {
		tickers = append(tickers, tk)
	}
	sort.Slice(tickers, func(i, j int) bool {
		if realized[tickers[i]] != realized[tickers[j]] {
			return realized[tickers[i]] > realized[tickers[j]]
		}
		return tickers[i] < tickers[j]
	})

	proposals := make([]cache.Proposal, 0, len(tickers))
	for i, tk := range tickers {
		proposals = append(proposals, cache.Proposal{
			Ticker: tk,
			Weight: realized[tk] / total,
			Rank:   i + 1,
		})
	}
	return proposals
}
