package autopilot

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/google/uuid"
)

const (
	ProposalDir  = "data/autopilot"
	ProposalFile = "data/autopilot/pending_proposal.json"

	StatusPending   = "pending"
	StatusConfirmed = "confirmed"
	StatusDismissed = "dismissed"
	StatusExpired   = "expired"
)

// Proposal represents a pending rebalance proposal generated by the autopilot pipeline.
type Proposal struct {
	ID        string    `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
	Status    string    `json:"status"`

	// Portfolio context
	Portfolio string `json:"portfolio"`  // golden copy path
	Strategy  string `json:"strategy"`   // e.g. "multibagger"
	Frequency string `json:"frequency"`  // e.g. "quarterly"

	// Changes from previous golden copy
	Entries       []StockChange `json:"entries"`        // new additions
	Exits         []StockChange `json:"exits"`          // removals
	WeightChanges []WeightDelta `json:"weight_changes"` // reweighted existing stocks

	// Proposed orders
	Orders      []ProposedOrder `json:"orders"`
	FilteredOut []ProposedOrder `json:"filtered_out"` // micro-transaction filtered

	// Summary
	TotalBuyValue  float64  `json:"total_buy_value"`
	TotalSellValue float64  `json:"total_sell_value"`
	EstimatedCost  float64  `json:"estimated_cost"`
	TaxWarnings    []string `json:"tax_warnings"`

	// Report references
	ReportPath    string `json:"report_path"`
	SelectionPath string `json:"selection_path"`

	// Execution results (filled after confirmation)
	ConfirmedAt    *time.Time     `json:"confirmed_at,omitempty"`
	ExecutionLog   []OrderResult  `json:"execution_log,omitempty"`
	ExecutionError string         `json:"execution_error,omitempty"`
}

// ProposedOrder represents a single order in the rebalance proposal.
type ProposedOrder struct {
	Ticker     string  `json:"ticker"`
	Exchange   string  `json:"exchange"`
	Action     string  `json:"action"` // "BUY" or "SELL"
	Quantity   int     `json:"quantity"`
	LimitPrice float64 `json:"limit_price"`
	Value      float64 `json:"value"`
}

// StockChange represents a stock entering or exiting the portfolio.
type StockChange struct {
	Ticker string  `json:"ticker"`
	Rank   int     `json:"rank"`
	Score  float64 `json:"score"`
	Weight float64 `json:"weight"`
	Reason string  `json:"reason"`
}

// WeightDelta represents a weight change for an existing holding.
type WeightDelta struct {
	Ticker    string  `json:"ticker"`
	OldWeight float64 `json:"old_weight"`
	NewWeight float64 `json:"new_weight"`
}

// OrderResult captures the outcome of placing a single order.
type OrderResult struct {
	Ticker  string `json:"ticker"`
	Action  string `json:"action"`
	OrderID string `json:"order_id,omitempty"`
	Success bool   `json:"success"`
	Error   string `json:"error,omitempty"`
}

// NewProposal creates a new proposal with the given TTL in days.
func NewProposal(portfolio, strategy, frequency string, ttlDays int) *Proposal {
	now := time.Now()
	return &Proposal{
		ID:        uuid.New().String(),
		CreatedAt: now,
		ExpiresAt: now.AddDate(0, 0, ttlDays),
		Status:    StatusPending,
		Portfolio: portfolio,
		Strategy:  strategy,
		Frequency: frequency,
	}
}

// IsExpired returns true if the proposal has passed its expiry time.
func (p *Proposal) IsExpired() bool {
	return time.Now().After(p.ExpiresAt)
}

// IsActionable returns true if the proposal can be confirmed or dismissed.
func (p *Proposal) IsActionable() bool {
	return p.Status == StatusPending && !p.IsExpired()
}

// SaveProposal persists the proposal to disk as JSON.
func SaveProposal(p *Proposal) error {
	if err := os.MkdirAll(ProposalDir, 0755); err != nil {
		return fmt.Errorf("creating autopilot directory: %w", err)
	}
	data, err := json.MarshalIndent(p, "", "  ")
	if err != nil {
		return fmt.Errorf("marshaling proposal: %w", err)
	}
	if err := os.WriteFile(ProposalFile, data, 0644); err != nil {
		return fmt.Errorf("writing proposal file: %w", err)
	}
	return nil
}

// LoadProposal reads the pending proposal from disk.
// Returns nil, nil if no proposal file exists.
func LoadProposal() (*Proposal, error) {
	data, err := os.ReadFile(ProposalFile)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("reading proposal file: %w", err)
	}
	var p Proposal
	if err := json.Unmarshal(data, &p); err != nil {
		return nil, fmt.Errorf("parsing proposal file: %w", err)
	}
	// Auto-expire if past TTL
	if p.Status == StatusPending && p.IsExpired() {
		p.Status = StatusExpired
		_ = SaveProposal(&p) // best-effort persist expiry
	}
	return &p, nil
}

// ConfirmProposal marks the proposal as confirmed and records the timestamp.
func ConfirmProposal(p *Proposal) error {
	if !p.IsActionable() {
		if p.IsExpired() {
			return fmt.Errorf("proposal %s has expired (expired at %s)", p.ID, p.ExpiresAt.Format(time.RFC3339))
		}
		return fmt.Errorf("proposal %s is not actionable (status: %s)", p.ID, p.Status)
	}
	now := time.Now()
	p.Status = StatusConfirmed
	p.ConfirmedAt = &now
	return SaveProposal(p)
}

// DismissProposal marks the proposal as dismissed without executing.
func DismissProposal(p *Proposal) error {
	if p.Status != StatusPending {
		return fmt.Errorf("proposal %s cannot be dismissed (status: %s)", p.ID, p.Status)
	}
	p.Status = StatusDismissed
	return SaveProposal(p)
}

// ArchiveProposal moves the current proposal to the archive directory.
func ArchiveProposal(p *Proposal) error {
	archiveDir := filepath.Join(ProposalDir, "archive")
	if err := os.MkdirAll(archiveDir, 0755); err != nil {
		return fmt.Errorf("creating archive directory: %w", err)
	}
	archiveName := fmt.Sprintf("%s_%s.json", p.CreatedAt.Format("20060102_150405"), p.Status)
	archivePath := filepath.Join(archiveDir, archiveName)

	data, err := json.MarshalIndent(p, "", "  ")
	if err != nil {
		return fmt.Errorf("marshaling proposal for archive: %w", err)
	}
	if err := os.WriteFile(archivePath, data, 0644); err != nil {
		return fmt.Errorf("writing archive file: %w", err)
	}
	// Remove the active proposal file
	_ = os.Remove(ProposalFile)
	return nil
}
