// Command depsgraph emits a Graphviz DOT dependency graph of the module's
// internal pkg/ packages, colored and rank-ordered by the R16 layer map.
//
// It is the visual companion to devtools/checkdeps: checkdeps gives a pass/fail
// verdict on the layering, depsgraph lets you *see* the graph — every internal
// edge, grouped into layer bands (L0 leaves at the bottom, L6 server at the
// top). An unexpected cross-package edge that technically passes checkdeps but
// smells wrong is obvious in the picture.
//
// Only internal edges (github.com/raghavkgarg/mycase/pkg/*) are drawn; stdlib
// and third-party imports are omitted to keep the graph about our own
// structure. The layer map is shared with checkdeps via
// devtools/internal/layers.
//
// Run:  go run ./devtools/depsgraph > deps.dot
//
//	go run ./devtools/depsgraph | dot -Tsvg -o deps.svg
//
// (wired into `make deps-graph`).
package main

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/raghavkgarg/mycase/devtools/internal/layers"
)

// layerColor gives each layer band a fill color (light → dark, low → high).
var layerColor = map[int]string{
	0: "#e3f2fd",
	1: "#c8e6c9",
	2: "#fff9c4",
	3: "#ffe0b2",
	4: "#ffccbc",
	5: "#f8bbd0",
	6: "#e1bee7",
}

func main() {
	pkgs, err := layers.List()
	if err != nil {
		fmt.Fprintf(os.Stderr, "depsgraph: %v\n", err)
		os.Exit(1)
	}

	// Collect nodes per layer and internal edges.
	byLayer := map[int][]string{}
	seen := map[string]bool{}
	type edge struct{ from, to string }
	var edges []edge

	for _, p := range pkgs {
		short := layers.Short(p.ImportPath)
		if _, known := layers.Layers[short]; !known {
			// Unknown package — checkdeps will flag it; show it in an "unplaced"
			// band (layer -1) rather than dropping it silently.
			if !seen[short] {
				byLayer[-1] = append(byLayer[-1], short)
				seen[short] = true
			}
		} else if !seen[short] {
			byLayer[layers.Layers[short]] = append(byLayer[layers.Layers[short]], short)
			seen[short] = true
		}

		for _, imp := range p.Imports {
			if !layers.IsInternal(imp) {
				continue
			}
			edges = append(edges, edge{from: short, to: layers.Short(imp)})
		}
	}

	// Emit DOT.
	var b strings.Builder
	b.WriteString("// Generated by devtools/depsgraph — internal pkg/ dependency graph.\n")
	b.WriteString("// Layers: L0 (leaves) at bottom → L6 (server) at top. Edges point to the imported package.\n")
	b.WriteString("digraph mycase_deps {\n")
	b.WriteString("  rankdir=BT;\n")
	b.WriteString("  node [shape=box, style=\"rounded,filled\", fontname=\"Helvetica\", fontsize=10];\n")
	b.WriteString("  edge [color=\"#90a4ae\", arrowsize=0.7];\n")
	b.WriteString("  graph [fontname=\"Helvetica\", labelloc=t, label=\"mycase pkg/ dependency graph (L0 leaves → L6 server)\"];\n\n")

	// One subgraph cluster per layer, drawn low → high, with same-rank nodes.
	for _, l := range layerBands(byLayer) {
		names := byLayer[l]
		sort.Strings(names)
		label, color := "unplaced (not in layer map)", "#ffcdd2"
		if l >= 0 {
			label = fmt.Sprintf("L%d", l)
			color = layerColor[l]
		}
		fmt.Fprintf(&b, "  subgraph cluster_L%d {\n", l+1) // +1 so -1 → cluster_L0-safe id
		fmt.Fprintf(&b, "    label=%q; style=filled; color=\"#eceff1\"; fontsize=12;\n", label)
		b.WriteString("    { rank=same;\n")
		for _, n := range names {
			fmt.Fprintf(&b, "      %q [fillcolor=%q];\n", n, color)
		}
		b.WriteString("    }\n")
		b.WriteString("  }\n\n")
	}

	// Edges (deduplicated, sorted for stable output).
	sort.Slice(edges, func(i, j int) bool {
		if edges[i].from != edges[j].from {
			return edges[i].from < edges[j].from
		}
		return edges[i].to < edges[j].to
	})
	edgeSeen := map[string]bool{}
	for _, e := range edges {
		key := e.from + "\x00" + e.to
		if edgeSeen[key] {
			continue
		}
		edgeSeen[key] = true
		fmt.Fprintf(&b, "  %q -> %q;\n", e.from, e.to)
	}

	b.WriteString("}\n")
	fmt.Print(b.String())
}

// layerBands returns the layer keys present, sorted ascending (-1 unplaced first).
func layerBands(byLayer map[int][]string) []int {
	var ls []int
	for l := range byLayer {
		ls = append(ls, l)
	}
	sort.Ints(ls)
	return ls
}
