package golden

import "time"

// GoldenRegime categorizes where a stock sits in the Golden Triangle.
type GoldenRegime string

const (
	RegimeGoldenCore     GoldenRegime = "GOLDEN_CORE"     // Full Trinity: High Quality + Launchpad Base + Valuation Cushion
	RegimeHighVelocity   GoldenRegime = "HIGH_VELOCITY"   // Quality + Momentum Coiling, but Multiple Overhang (< -20%)
	RegimeValueBreakout  GoldenRegime = "VALUE_BREAKOUT"  // Deep Value (+20%+) waking up with early Stage-1 Accumulation
	RegimeCompounderSale GoldenRegime = "COMPOUNDER_SALE" // High Quality (MB >= 60) + Value (+10%+), but no active base yet
	RegimeMonitor        GoldenRegime = "MONITOR"          // General cohort monitor
)

// GoldenConstituent represents a single stock evaluated across the Golden Triangle.
type GoldenConstituent struct {
	Ticker           string       `json:"ticker"`
	Sector           string       `json:"sector"`
	MBScore          *float64     `json:"mb_score,omitempty"`
	MBPassedStage1   bool         `json:"mb_passed_stage1"`
	EMBScore         *float64     `json:"emb_score,omitempty"`
	EMBPassedStage1  bool         `json:"emb_passed_stage1"`
	VCPRatio         *float64     `json:"vcp_ratio,omitempty"`
	DeliveryDelta    *float64     `json:"delivery_delta,omitempty"`
	RVOLZScore       *float64     `json:"rvol_z_score,omitempty"`
	CMP              *float64     `json:"cmp,omitempty"`
	FairPrice        *float64     `json:"fair_price,omitempty"`
	UpsidePct        *float64     `json:"upside_pct,omitempty"`
	MOSVerdict       string       `json:"mos_verdict,omitempty"`
	ValidModelCount  int          `json:"valid_model_count"`
	ValuationScore   float64      `json:"valuation_score"`
	CompositeScore   float64      `json:"composite_score"`
	Regime           GoldenRegime `json:"regime"`
	DiagnosticAction string       `json:"diagnostic_action"`
}

// GoldenCensus records the count distribution across the 4 triangle regimes.
type GoldenCensus struct {
	TotalEvaluated      int     `json:"total_evaluated"`
	GoldenCoreCount     int     `json:"golden_core_count"`
	HighVelocityCount   int     `json:"high_velocity_count"`
	ValueBreakoutCount  int     `json:"value_breakout_count"`
	CompounderSaleCount int     `json:"compounder_sale_count"`
	MonitorCount        int     `json:"monitor_count"`
	CohortMedianUpside  float64 `json:"cohort_median_upside"`
}

// GoldenReport represents the full analysis report generated by the Golden Triangle engine.
type GoldenReport struct {
	AsOfDate       time.Time           `json:"as_of_date"`
	IndexName      string              `json:"index_name"`
	Census         GoldenCensus        `json:"census"`
	GoldenCore     []GoldenConstituent `json:"golden_core"`
	HighVelocity   []GoldenConstituent `json:"high_velocity"`
	ValueBreakouts []GoldenConstituent `json:"value_breakouts"`
	CompounderSale []GoldenConstituent `json:"compounder_sale"`
	OverhangAlerts []GoldenConstituent `json:"overhang_alerts"`
	AllRanked      []GoldenConstituent `json:"all_ranked"`
}
